services:
  db:
    image: postgres:16
    env_file:
      - .env
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: node-app
    ports:
      - "3001:3001"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: db

volumes:
  postgres_data:

